config = {
    "histos": {
        "N_BINS": [
            400,
            400,
            400,
            400,
            600,
            600,
            600,
            600,
            800,
            800,
            800,
            800,
            1000,
            1000,
            1600,
        ],
        "BIN_LOW": [
            0,
            0,
            0,
            0,
            -3,
            -3,
            -3,
            -3,
            -4,
            -4,
            -4,
            -4,
            0,
            0,
            0,
        ],
        "BIN_HIGH": [
            2000,
            2000,
            2000,
            2000,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            5000,
            5000,
            8000,
        ],
        "HISTO_NAMES": [
            "pt_leadlep",
            "pt_subleadlep",
            "pt_leadjet",
            "pt_subleadjet",
            "eta_leadlep",
            "eta_subleadlep",
            "eta_leadjet",
            "eta_subleadjet",
            "phi_leadlep",
            "phi_subleadlep",
            "phi_leadjet",
            "phi_subleadjet",
            "mass_dileptons",
            "mass_dijets",
            "mass_fourobject",
        ],
        "HISTO_LABELS": [
            "p_{T} of the leading lepton [GeV]",
            "p_{T} of the subleading lepton [GeV]",
            "p_{T} of the leading jet [GeV]",
            "p_{T} of the subleading jet [GeV]",
            "#eta of the leading lepton",
            "#eta of the subleading lepton",
            "#eta of the leading jet",
            "#eta of the subleading jet",
            "#phi of the leading lepton",
            "#phi of the subleading lepton",
            "#phi of the leading jet",
            "#phi of the subleading jet",
            "m_{ll} [GeV]",
            "m_{jj} [GeV]",
            "m_{lljj} [GeV]",
        ],
    },
}
